<a href="https://colab.research.google.com/github/CostaNathan/doctorate/blob/Introdu%C3%A7%C3%A3o_Python/Aula_1_pt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introdução à Python - Aula 1


In [1]:
# imprtar as bibliotecas

import numpy as np
import matplotlib.pyplot as plt

In [2]:
vetor = np.linspace(0,5,10)
vetor

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [3]:
b = np.ones(2)
b

array([1., 1.])

### Variáveis

In [4]:
a = 5
b = 'cinco'
c = 5.0

### Espaços brancos

In [6]:
for i in range (5):
  if i < 5:
    print('Olá')
    print('Seja bem vindo', i)
    print(i*10) 


Olá
Seja bem vindo 0
0
Olá
Seja bem vindo 1
10
Olá
Seja bem vindo 2
20
Olá
Seja bem vindo 3
30
Olá
Seja bem vindo 4
40


Cortando arrays

In [8]:
lista = [0, 1. , 'texto'] # criar lista 
myvals = np.array([1, 2, 3, 4]) # transforma lista em array
myvals[1:3] # filtra as posições dos elementos desejados

array([2, 3])

### Atribuição de variável array

In [10]:
a = np.linspace(1,5,5)
b = a # cria um espelho
b[4] = 1 # modifica tanto b quanto a por ser um espelho
print(a, b)

c = a.copy() # cria uma copia estática 
c[4] = 4
print(a,b,c)

[1. 2. 3. 4. 1.] [1. 2. 3. 4. 1.]
[1. 2. 3. 4. 1.] [1. 2. 3. 4. 1.] [1. 2. 3. 4. 4.]
